Error: Provider produced inconsistent final plan
```
  # module.k8sbase.helm_release.autoscaler will be updated in-place
  ~ resource "helm_release" "autoscaler" {
        id                         = "cluster-autoscaler"
        name                       = "cluster-autoscaler"
      ~ values                     = [
          - <<-EOT
                "autoDiscovery":
                  "clusterName": "opta-live-example"
                "awsRegion": "us-east-1"
                "rbac":
                  "serviceAccount":
                    "annotations":
                      "eks.amazonaws.com/role-arn": "arn:aws:iam::889760294590:role/opta-live-example-k8s-autoscaler"
                    "name": "autoscaler"
            EOT,
        ] -> (known after apply)
      + wait_for_jobs              = false
        # (25 unchanged attributes hidden)
    }
.
.
.

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.k8sbase.helm_release.autoscaler to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/helm" produced an invalid new value for .wait_for_jobs: was
│ cty.False, but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```